version: "3.9"

services:
  database:
    container_name: postgres_testing
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.15.0
    container_name: nginx_testing
    build:
      context: ./nginx
    working_dir: /backend
    volumes:
      - ./../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/environment/local/sites/:/etc/nginx/sites-available
      - ./nginx/environment/local/conf.d/:/etc/nginx/conf.d
      #      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    build:
      context: ../docker/php-fpm
    volumes:
      - ../backend:/symfony
    container_name: php_fpm_testing
